# Generated by Django 2.2.19 on 2023-09-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230925_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'units')},
        ),
    ]
